baseURL = "http://lowelltech.io/"
defaultContentLanguage = "en"
languageCode = "en-us"
title = "Lowell Tech | Microsoft Azure Cloud Blog"
theme = "gokarna"
enableRobotsTXT = true

[params]
  # URL for the avatar on homepage
  avatarURL = "/images/avatar.png"

  # Choose one of size-xs, size-s, size-m, size-l & size-xl. (Default: size-m)
  avatarSize = "size-m"

  # Description to display on homepage
  description = "I'm a Sr. Cloud Solution Architect at Microsoft with a focus in Azure Core architecture."

  # Accent color is displayed when you hover over <a> tags
  accentColor = "#1a73f7"

  # You can use this to inject any HTML in the <head> tag.
  # Ideal usecase for this is to import custom js/css or add your analytics snippet
  customHeadHTML = ""

  # Keywords relevant for SEO
  metaKeywords = ["blog", "Azure", "Microsoft", "Ryan Lowell", "Cloud", "Cloud Solution Architect", "Senior"]

  # If you want to display posts on the homepage, the options are
  # "popular" (order posts by weight), "recent" (order posts by date)
  # or "" (do not display, default option)
  showPostsOnHomePage = "recent"

  # Footer text
  footer = "Ryan Lowell | Lowell Tech"

  togglePreviousAndNextButtons = "true"

[menu]
    # We use feather-icons: https://feathericons.com/

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about_me/"
    weight = 3
    
  [[menu.main]]
    identifier = "github"
    url = "https://github.com/rlowellfl"
    weight = 4
    pre = "<span data-feather='github'></span>"

  [[menu.main]]
    identifier = "linkedin"
    url = "https://www.linkedin.com/in/rrlowell/"
    weight = 5
    pre = "<span data-feather='linkedin'></span>"

  [[menu.main]]
    identifier = "twitter"
    url = "https://twitter.com/RyanLowellFL"
    weight = 6
    pre = "<span data-feather='twitter'></span>"

  [[menu.main]]
    identifier = "buymeacoffee"
    pre = "<span data-feather='coffee'></span>"
    url = "https://www.buymeacoffee.com/lowtech"
    weight = 7