baseURL = "https://lowelltech.io/"
defaultContentLanguage = "en"
languageCode = "en-us"
title = "Lowell Tech   |   Microsoft Azure Cloud Blog"
theme = "gokarna"
enableRobotsTXT = true

[params]

  avatarURL = "/images/avatar.png"
  metaKeywords = ["blog", "Azure", "Microsoft", "Ryan Lowell", "Cloud", "Cloud Solution Architect", "Senior"]
  showPostsOnHomePage = "recent"
  avatarSize = "size-m"
  description = "I'm Ryan Lowell, a Sr. Cloud Solution Architect at Microsoft. My particular area of focus is architecture, engineering, security, governance, and technical training on Azure. I truly enjoy helping companies build and expand their infrastructure in the Microsoft cloud. During my nearly 20-year technology career I have worked across many areas of IT including professional and managed services, security implementation, project delivery, technical training, system administration, and technical presales."

  # Accent color is displayed when you hover over <a> tags
  accentColor = "#1a73f7"

  customHeadHTML = '''
    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-Q10MK9N3PR"></script>
    <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
    gtag('config', 'G-Q10MK9N3PR');
    </script>
  '''

  footer = "Ryan Lowell | Lowell Tech"
  togglePreviousAndNextButtons = "true"

  customFooterHTML = '''
    <script src="https://utteranc.es/client.js"
    repo="rlowellfl/website_blog"
    issue-term="pathname"
    theme="github-dark"
    crossorigin="anonymous"
    async>
    </script>
  '''

[menu]
    # We use feather-icons: https://feathericons.com/

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about_me/"
    weight = 3
    
  [[menu.main]]
    identifier = "github"
    url = "https://github.com/rlowellfl"
    weight = 4
    pre = "<span data-feather='github'></span>"

  [[menu.main]]
    identifier = "linkedin"
    url = "https://www.linkedin.com/in/rrlowell/"
    weight = 5
    pre = "<span data-feather='linkedin'></span>"

  [[menu.main]]
    identifier = "twitter"
    url = "https://twitter.com/RyanLowellFL"
    weight = 6
    pre = "<span data-feather='twitter'></span>"

  [[menu.main]]
    identifier = "buymeacoffee"
    pre = "<span data-feather='coffee'></span>"
    url = "https://www.buymeacoffee.com/lowtech"
    weight = 7